# Generated by Django 2.0.7 on 2018-07-16 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streamapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserModel',
        ),
    ]
